In [10]:
# ==============================
# Clean Expenses Notebook
# ==============================

import pandas as pd

# 1) Load data
df = pd.read_csv("expenses.csv")

print("Original shape:", df.shape)
df.head()

Original shape: (30, 6)

,date,type,category,amount,payment_method,description
0,2026-01-01,income,Income,1200000,transfer,Monthly salary
1,2026-01-01,expense,Bills,85000,cash,Internet subscription
2,2026-01-02,expense,Food,18000,cash,Grocery items
3,2026-01-02,expense,Transport,5000,cash,Taxi ride
4,2026-01-03,expense,Shopping,25000,card,House supplies

In [11]:
# 2) Basic column check
required_cols = ['date', 'category', 'amount']

for col in required_cols:
    if col not in df.columns:
        raise ValueError(f"Missing required column: {col}")

print("All required columns exist.")

All required columns exist.

In [12]:
# 3) Clean date column
df['date'] = pd.to_datetime(df['date'], errors='coerce')
df = df.dropna(subset=['date'])

In [13]:
# 4) Validate amount column
def validate_amount(x):
    try:
        x = float(x)
        return x if x > 0 else None
    except:
        return None

df['amount'] = df['amount'].apply(validate_amount)
df = df.dropna(subset=['amount'])

In [14]:
# 5) Normalize category
df['category'] = df['category'].astype(str).str.strip().str.lower()

In [15]:
# 6) Derived columns
df['day_of_week'] = df['date'].dt.day_name()
df['week'] = df['date'].dt.isocalendar().week
df['is_weekend'] = df['date'].dt.weekday >= 5

In [16]:
# 7) Final check
print("Cleaned shape:", df.shape)
df.head()

Cleaned shape: (30, 9)

,date,type,category,amount,payment_method,description,day_of_week,week,is_weekend
0,2026-01-01,income,income,1200000.0,transfer,Monthly salary,Thursday,1,False
1,2026-01-01,expense,bills,85000.0,cash,Internet subscription,Thursday,1,False
2,2026-01-02,expense,food,18000.0,cash,Grocery items,Friday,1,False
3,2026-01-02,expense,transport,5000.0,cash,Taxi ride,Friday,1,False
4,2026-01-03,expense,shopping,25000.0,card,House supplies,Saturday,1,True

In [17]:
# 8) Save clean data
df.to_csv("clean_expenses.csv", index=False)

print("clean_expenses.csv saved successfully.")

clean_expenses.csv saved successfully.