Preparing Features and Labels (X, y) for Machine Learning

In [1]:
import pandas as pd

# -----------------------------
# 1) Create a simple dataset
# -----------------------------
df = pd.DataFrame({
    "day": [1, 2, 3, 4, 5, 6, 7],
    "category": ["Food", "Transport", "Food", "Bills", "Food", "Other", "Transport"],
    "amount": [12000, 5000, 8000, 25000, 7000, 4000, 6000],
    "weekly_total": [67000, 67000, 67000, 67000, 67000, 67000, 67000]  # مثال بسيط
})

df

   day   category  amount  weekly_total
0    1       Food   12000         67000
1    2  Transport    5000         67000
2    3       Food    8000         67000
3    4      Bills   25000         67000
4    5       Food    7000         67000
5    6      Other    4000         67000
6    7  Transport    6000         67000

In [2]:
# -----------------------------
# 2) Choose features
# -----------------------------
# Features: day + category
X = df[["day", "category"]]

# Convert category to one-hot
X = pd.get_dummies(X, columns=["category"])

X.head()

   day  category_Bills  category_Food  category_Other  category_Transport
0    1           False           True           False               False
1    2           False          False           False                True
2    3           False           True           False               False
3    4            True          False           False               False
4    5           False           True           False               False

In [9]:
# -----------------------------
# 2) Choose features
# -----------------------------
# Features: day + category
X = df[["day", "category"]]

# Convert category to one-hot
X = pd.get_dummies(X, columns=["category"])
X = X.astype(int)
X.head()

   day  category_Bills  category_Food  category_Other  category_Transport
0    1               0              1               0                   0
1    2               0              0               0                   1
2    3               0              1               0                   0
3    4               1              0               0                   0
4    5               0              1               0                   0

In [4]:
# -----------------------------
# 3) Choose label (target)
# -----------------------------
y = df["amount"]

y.head()

0    12000
1     5000
2     8000
3    25000
4     7000
Name: amount, dtype: int64

In [5]:
# -----------------------------
# 4) Split X, y
# -----------------------------
# X already prepared, y already prepared
print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (7, 5)
y shape: (7,)

In [6]:
# -----------------------------
# 5) Validate X and y
# -----------------------------
print("Missing values in X:", X.isna().sum().sum())
print("Missing values in y:", y.isna().sum())

print("\nX columns:", list(X.columns))

Missing values in X: 0
Missing values in y: 0

X columns: ['day', 'category_Bills', 'category_Food', 'category_Other', 'category_Transport']

Trying a Different Target (weekly_total)

In [7]:
y2 = df["weekly_total"]

print("X shape:", X.shape)
print("y2 shape:", y2.shape)

y2.head()

X shape: (7, 5)
y2 shape: (7,)

0    67000
1    67000
2    67000
3    67000
4    67000
Name: weekly_total, dtype: int64